version: "3"

services:
  localstack:
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=sns,sqs,s3,lambda,dynamodb,kinesis,kms
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CORS_HANDLERS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=authorization,content-type,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-invocation-type,x-amz-log-type
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack:/etc/localstack/init/ready.d
    networks:
      - dev

networks:
  dev:
